version: "3.4"
services:
  service:
    build: ./service
    restart: always
    volumes:
      - "env:/env"
  updater:
    build: ./updater
    volumes:
      - "env:/env"
  watcher:
    build: ./watcher
    volumes:
      - "env:/env"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  env:
    external: false
    name: env
