version: "3.4"
services:
  service:
    build: ./service
    restart: always
    volumes:
      - "env:/env"
  updater:
    build: ./updater
    volumes:
      - "env:/env"
volumes:
  env:
    external: false
    name: env
