version: "3.4"
services:
  service:
    build: ./service
    volumes:
      - "env:/env"
  watcher:
    build: ./watcher
    volumes:
      - "env:/env"
volumes:
  env:
    external: false
    name: env
